apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv-cypress
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 200Mi
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-07710dd1791db2311
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cypress-sc
