apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /c/Users/BenardSilomaMasikond/Desktop/kubernetes/jenkinsData # Replace with your local path