apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-app
  namespace: cypress 
  labels:
    app: ui-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-app
  template:
    metadata:
      name: ui-app
      labels:
        app: ui-app
    spec:
      containers:
        - name: ui-app
          image: silomaben/ui-dummy
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          volumeMounts:
          - name: cypress-vol
            mountPath: /shared/cypress/reports
      volumes:
        - name: cypress-vol
          persistentVolumeClaim: 
            claimName: efs-shared
      restartPolicy: Always
