apiVersion: v1
kind: Service
metadata:
  name: ui-app-service
  namespace: cypress 
spec:
  selector:
    app: ui-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 30005
      nodePort: 30005
  type: NodePort