apiVersion: batch/v1
kind: Job
metadata:
  namespace: cypress
  name: e2e-test-app-job
spec:
  template:
    metadata:
      name: e2e-test-app-pod
    spec:
      containers:
        - name: e2e-test-app
          image: silomaben/tests-cypress
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          volumeMounts:
            - name: cypress-vol
              mountPath: /shared/cypress/reports
      restartPolicy: Never
      volumes:
        - name: cypress-vol
          persistentVolumeClaim: 
            claimName: cypress-pvc