apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-app
  namespace: cypress
  labels:
    app: express-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-app
  template:
    metadata:
      name: express-app
      labels:
        app: express-app
    spec:
      containers:
        - name: express-app
          image: silomaben/express-api
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
      restartPolicy: Always

