apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-app
  namespace: cypress
  labels:
    app: express-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-app
  template:
    metadata:
      name: express-app
      labels:
        app: express-app
    spec:
      containers:
        - name: express-app
          image: silomaben/express-api
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
      restartPolicy: Always

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv-cypress
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 200Mi
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-07710dd1791db2311
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cypress-sc

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cypress-pvc
  namespace: cypress
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
  storageClassName: cypress-sc
  volumeMode: Filesystem
  volumeName: efs-pv-cypress

